# Generated by Django 5.2.5 on 2025-10-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from prescription image using OCR'),
        ),
    ]
